kind: Deployment
apiVersion: apps/v1
metadata:
  creationTimestamp: null
  name: mw-kube-apm-demo23
  namespace: default
spec:
  selector:
    matchLabels:
      app: mw-app
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: mw-app
        k8s-app: mw-app
      creationTimestamp: null
    spec:
      containers:
        - args: 
          - node 
          - features/log.js
          env:
            - name: MW_AGENT_SERVICE
              value: mw-service.mw-agent-ns-xusuu.svc.cluster.local
            - name: MW_AUTOGENERATE_LOGGING_DATA
              value: "true"
          image: ghcr.io/middleware-labs/demo-apm-nodejs
          imagePullPolicy: Always
          name: mw-nodejs-apm-log-demo
          resources: {}
      restartPolicy: Always
