kind: Deployment
apiVersion: apps/v1
metadata:
  creationTimestamp: null
  name: mw-kube-apm
  namespace: default
spec:
  selector:
    matchLabels:
      app: mw-app
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: mw-app
        k8s-app: mw-app
      creationTimestamp: null
    spec:
      containers:
        - args: 
          - node 
          - features/log.js
          env:
            - name: MW_AGENT_SERVICE
              value: TARGET_MW_AGENT_SERVICE
          image: ghcr.io/middleware-labs/demo-apm-nodejs
          imagePullPolicy: Always
          name: mw-kube-agent
          resources: {}
      restartPolicy: Always
