version: "3.4"
services:  
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: 'todo'
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOST: localhost
      POSTGRES_USER: otel-demo
      POSTGRES_PASSWORD: otel-demo
    network_mode: host
    volumes:
      - ./todo:/docker-entrypoint-initdb.d

  node-apm-demo:
    build:
      context: ./
    # image: ghcr.io/middleware-labs/agent-node-apm:new
    command: node app.js
    environment:
      MYSQL_HOST: localhost
      MW_AUTOGENERATE_TRACING_DATA: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: 127.0.0.1:9319
      POSTGRES_HOST: localhost
      POSTGRES_DB: todo
      POSTGRES_USER: otel-demo
      POSTGRES_PASSWORD: otel-demo
    network_mode: host
    depends_on:
      - postgresql
    ports:
      - 3002:3002
